#!/bin/sh

# Emacs-IDE package installation

# Copyright (C) 2008-2014 Cédric Marie

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

VERSION=1.12.1
if [ ! -f eide-$VERSION.tar ]; then
  printf "\033[1;31meide-$VERSION.tar does not exist\033[0m\n"
  exit 1
fi

printf "\033[1mInstall package eide-$VERSION.tar\033[0m\n"
# --batch: don't use interactive display (implies -q: don't load ~/.emacs)
# --execute: execute package-install-file command
if ! /home/g093316/emacs/emacs-24.3/src/emacs-24.3.1 --batch --execute "(package-install-file \"$PWD/eide-$VERSION.tar\")" ; then
  printf "\n\033[1;31mInstallation failed\033[0m\n"
  exit 1
fi
printf "\n\033[1mInstructions for enabling Emacs-IDE\033[0m\n"
printf "You must add the following lines in your ~/.emacs:\n\n"
printf "(package-initialize)\n"
printf "(eide-start)\n\n"
printf "NB: (package-initialize) might already be present and should not be added in that case.\n"
