#!/usr/bin/env sh

# Uninstallation script for Emacs-IDE

# Copyright (C) 2008-2013 Cédric Marie

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

option_local=0
while getopts l OPT
do
  case $OPT in
    l) option_local=1;;
    *) exit 1;;
  esac
done
shift $(($OPTIND - 1))

if [ $option_local -eq 0 ]; then
  printf "\033[1mCheck root privileges:\033[0m "
  if [ $(id -u) -eq 0 ]; then
    printf "\033[1;32mOK\033[0m\n\n"
  else
    printf "\033[1;31mFAILED: You need root privileges to uninstall\033[0m\n"
    printf "If Emacs-IDE was installed locally for this user (install -l), you should use -l option\n"
    exit 1
  fi
fi

printf "\n\033[1mUninstall Emacs-IDE\033[0m\n"
if [ $option_local -eq 0 ]; then
  if [ -f /usr/local/share/emacs/site-lisp/eide.elc ]; then
    rm -vf /usr/local/share/emacs/site-lisp/eide.elc
    rm -vf /usr/local/share/emacs/site-lisp/eide-*.elc
  elif [ -f /usr/share/emacs/site-lisp/eide.elc ]; then
    rm -vf /usr/share/emacs/site-lisp/eide.elc
    rm -vf /usr/share/emacs/site-lisp/eide-*.elc
  else
    printf "\033[1;31mERROR: Emacs-IDE is installed neither in /usr/local/share/emacs/site-lisp nor in /usr/share/emacs/site-lisp\033[0m\n"
    exit 1
  fi
else
  if [ -f ~/.emacs.d/site-lisp/eide.elc ]; then
    rm -vf ~/.emacs.d/site-lisp/eide.elc
    rm -vf ~/.emacs.d/site-lisp/eide-*.elc
  else
    printf "\033[1;31mERROR: Emacs-IDE is not installed in ~/.emacs.d/site-lisp\033[0m\n"
    exit 1
  fi
fi

printf "\n\033[1mInstructions for disabling Emacs-IDE\033[0m\n"
printf "You must remove following lines from your ~/.emacs:\n\n"
printf "(require 'eide)\n"
printf "(eide-start)\n"

if [ $option_local -eq 1 ]; then
  printf "\nYou can also remove following line if it was used by Emacs-IDE only:\n\n"
  printf "(add-to-list 'load-path \"~/.emacs.d/site-lisp/\")\n"
fi
